name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Old version
      
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Old version
        with:
          node-version: 14  # Older Node.js version
